### ISSUE TITLE
TODOs and docs for testing fastapi as backend

### ISSUE THREAD

**Issue by mtrazzi** [EleutherAGI/eegi-backend#2]
### TODOs:
- [x] write some [basic authentification](https://fastapi.tiangolo.com/tutorial/security/first-steps/) to see how this works
- [x] check how databases work by adding one manual element in our first fastapi database
- [x] send human input from our [current frontend](https://github.com/EleutherAGI/eegi-web-app) to the backend's database

### Current notes
- [eegi v2](https://docs.google.com/document/d/18pmJBgiucNCg3PJoud3zNTc4qsq5tvcS_WZ9ltsuDMY/edit)
- [13/05 Meeting Notes](https://docs.google.com/document/d/1QJPTU7ctJuwaXErZZ3bZyrdFYxhppRJbtb_QCMSU9O8/edit?usp=sharing)
- [website backend discussion](https://docs.google.com/document/d/1OYn_SGJeZcsTMvLdeuE73PQRvSbm9iAJDtxP6__fxGI/edit)

**Comment by kipgparker** [comment]
Yep, basic authentication will be done with OAuth2 JWT tokens I think.

For now, I don't think it makes sense to make a management page for users, but we can just edit raw DB. (But this can of course be added once we have a simple version)

Still need to figure out we want to give people access to it, I quite like the idea of generating private keys and sharing them out.

DB will probably be using Postgresql with SQLAlchemy, then we can connect up the front end while we have a basic implementation.
